### ISSUE TITLE
Channel count seems confusing / misleading

### ISSUE THREAD

**Issue by xanoni** [Czino/lnstats#4]
The output starts with `You opened XX channels, closed XY channels, ...`.

I think this is a bit misleading. As far as I understand, `XX` and `YY` mean the below:

- `XX`: number of LIVE channels that are self-initiated (vs. opened by peers)
- `YY`: number of CLOSED channels that were originally opened by ourselves

Thus, shouldn't the output say instead:

`You opened XX+YY channels, out of which YY are now closed, ...`.

?

PR here: https://github.com/Czino/lnstats/pull/3

**Comment by Czino** [comment]
Indeed, I see that flaw in my previous assumption. Well spotted 👍
